apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: scrapyd
  name: scrapyd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scrapyd
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: scrapyd
    spec:
      containers:
        - image: sg1userdocker/python_scrapyd
          name: scrapyd
          ports:
            - containerPort: 6800
          resources: {}
      restartPolicy: Always
status: {}
