apiVersion: v1
kind: Service
metadata:
  labels:
    visualize: "true"
  name: spring-boot-kafka-kubernetes-load-balancer
spec:
  selector:
    app: spring-boot-kafka-kubernetes-demo
  ports:
    - name: http
      protocol: TCP
      port: 9999
      targetPort: 9999
  type: LoadBalancer