apiVersion: v1
kind: Service
metadata:
  name: spring-boot-kafka-kubernetes-cluster-ip

spec:
  selector:
    app: spring-boot-kafka-kuberetes-demo
  ports:
    - name: http
      protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP
